# Generated by Django 4.0.1 on 2025-02-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssnacks', models.CharField(max_length=200)),
                ('veg_or_nonveg', models.CharField(max_length=200)),
                ('description', models.CharField(default=None, max_length=500)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image_url', models.CharField(default=False, max_length=2083)),
                ('follow_author', models.CharField(blank=True, max_length=2083)),
                ('book_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_snacks1', models.CharField(max_length=200)),
                ('s_price1', models.CharField(max_length=200)),
                ('s_image_url', models.CharField(default=False, max_length=2083)),
                ('ccardno1', models.CharField(max_length=20)),
                ('Expires', models.CharField(max_length=10)),
                ('CSC', models.CharField(max_length=20)),
                ('F_name', models.CharField(max_length=20)),
                ('Address1', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State1', models.CharField(max_length=20)),
                ('Post_code', models.CharField(max_length=20)),
                ('Mobile_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regis1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=200)),
                ('eEmail', models.CharField(max_length=200)),
                ('sphone', models.CharField(max_length=12)),
                ('sAddress', models.CharField(max_length=200)),
                ('sCode', models.CharField(max_length=200)),
                ('sAgree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snacks', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snacks.food1')),
            ],
        ),
    ]
